### ISSUE TITLE
bij de matches laden de genres incorrect in (database branch)

### ISSUE THREAD

**Issue by Txai-HvA** [Juliusmeeuwisse/blok-tech-crocmeisters#16]
/matches
- bij de matches laden de genres incorrect in (elke gebruiker krijgt dezelfde genres gek genoeg). Ik had geprobeerd de array genres te legen aan het einde van de loop, zodat die weer gevuld werd met genres de volgende match. Gek genoeg blijft de genres array hierdoor altijd leeg.
https://github.com/Juliusmeeuwisse/blok-tech-crocmeisters/blob/database/src/controllers/matchDataController.js

**Comment by joeriBouwman25** [comment]
het lijkt er op dat hij de lege array in currentgenres gebruikt omdat je de variabele include en niet de functie die de variabele zou moeten aanpassen

**Comment by Txai-HvA** [comment]
Op regel 37 wordt de **genresController.getUserGenres(matches[i].id)** methode aangeroepen. In deze methode wordt **currentUserGenres** gevuld in de genresController. Op regel 38 van genresController wordt genres gevuld met die array (currentUserGenres).

Alleen Stijn zou genres moeten krijgen in deze screenshot
![screenshot](https://i.gyazo.com/2a9c34e57ad6d203910451ad1e3dce8e.png)

**Comment by Txai-HvA** [comment]
Nadat ik een student-assistent had ingeschakeld, heb ik dit opgelost

**Comment by StijnvF** [comment]
top!
