### ISSUE TITLE
geen mail ontvangen bij maken nieuw account

### ISSUE THREAD

**Issue by joeriBouwman25** [Juliusmeeuwisse/blok-tech-crocmeisters#18]
Om de inlog flow te testen had ik mijzelf uit de database gehaald, met de nodemailer moet ik een bevestigings mail krijgen maar die kreeg ik niet, lijkt misschien nog wat mis te gaan

**Comment by StijnvF** [comment]
@joeriBouwman25, om even te checken dan. Heb jij wel de .env aangepast?

**Comment by joeriBouwman25** [comment]
zo goeiemorgen, ja daar gaat het mis nevermind haha!

**Comment by StijnvF** [comment]
Ah top!
