### ISSUE TITLE
Email README.md Txai

### ISSUE THREAD

**Issue by StijnvF** [Juliusmeeuwisse/blok-tech-crocmeisters#19]
Txai ik was even de readme aan t updaten, wist jouw hva email niet. Kan jij die er zelf ff aan toevoegen?

**Comment by StijnvF** [comment]
Waarschijnlijk gewoon je naam natuurlijk, maar just to be sure.

**Comment by Txai-HvA** [comment]
Done

**Comment by StijnvF** [comment]
Top, thanks!
